version: '3'



services:

  db: 
    image: postgres:15.1
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET: ${SECRET}
      
  
    networks:
      - db

    restart: unless-stopped
  
  web:
    image: finnrg/letsscience-backend:latest
    ports:
      - 3000:3000
    
    env_file:
      - ./.env

    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - web
      - db
    restart: unless-stopped

  proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/snginx/ssl:/etc/nginx/ssl
      - ./config/nginx/html:/usr/share/nginx/html

    restart: unless-stopped
    depends_on:
      - web
      - db

    networks:
      - web

networks:
   web:
   db:

